/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openrndr_opendmx_Native */

#ifndef _Included_org_openrndr_opendmx_Native
#define _Included_org_openrndr_opendmx_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openrndr_opendmx_Native
 * Method:    connect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_openrndr_opendmx_Native_connect
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_openrndr_opendmx_Native
 * Method:    disconnect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_openrndr_opendmx_Native_disconnect
  (JNIEnv *, jclass);

/*
 * Class:     org_openrndr_opendmx_Native
 * Method:    send
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_openrndr_opendmx_Native_send
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
